name: Build Linux Client

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'client/**'
      - '.github/workflows/build-linux.yml'
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - 'client/**'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libcurl4-openssl-dev libcjson-dev libmnl-dev

      - name: Configure CMake
        run: cmake -B client/build -S client -DCMAKE_BUILD_TYPE=Release

      - name: Build Linux Client
        run: cmake --build client/build

      - name: Upload Linux Client Artifact
        uses: actions/upload-artifact@v4
        with:
          name: auth-wg-linux-client
          path: client/build/vpn-client
